[package]
name = "lexer"
version = "0.1.0"
authors = ["nathanfaucett <nathanfaucett@gmail.com>"]

keywords = ["plugins", "plugin", "lexer"]
description = "plugin based lexer"
license = "MIT"
readme = "README.md"
repository = "https://github.com/nathanfaucett/rs-lexer.git"
homepage = "https://github.com/nathanfaucett/rs-lexer"

[dependencies]
[dev-dependencies]
