[package]
name = "lexer"
version = "0.1.0"
authors = ["nathanfaucett <nathanfaucett@gmail.com>"]

keywords = ["plugins", "plugin", "lexical", "reader"]
description = "plugin based lexical reader"
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/nathanfaucett/rs-lexer.git"
homepage = "https://gitlab.com/nathanfaucett/rs-lexer"

[dependencies]
collection_traits = {git = "https://gitlab.com/nathanfaucett/rs-collection_traits.git"}

[dev-dependencies]
